providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --network-timeout=1000000"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve@latest -s dist/endpoint-project -l tcp://0.0.0.0:$PORT"
